### ISSUE TITLE
Indication of duplicate names is incorrect

### ISSUE THREAD

**Issue by aus-betz** [danyill/oscd-rename-ieds#3]
It appears that when duplicate names are detected, the first IED in the list is always highlighted as being one of the duplicates, even though it is not involved. 

![image](https://github.com/user-attachments/assets/d12618c1-c881-46ff-864f-efe9d50b7d86)

**Comment by danyill** [comment]
It is annoying... also reported here: https://github.com/transpower-nz/open-scd/issues/19

I think what is happening is that it jumps to the top of the form when there's an error on the input. 

https://github.com/material-components/material-web/blob/main/docs/components/text-field.md#validation

We're doing custom validity. I expect it's not being done as well as it should be.
I will take a look.

https://github.com/danyill/oscd-rename-ieds/blob/41bc5b6eb71813f1d7afbbd992ec65dcad850e98/oscd-rename-ieds.ts#L176-L199

I note in passing:

* There's no need to return any values from this function
* I don't know we're doing `reportValidity` as well, I don't think that should be necessary

**Comment by danyill** [comment]
Ah. We're using `reportValidity` so the discrepancy is immediately alerted to the user.

Would it be better if it only came up when the user tries to click the button at the end?

Often the user wants to copy and paste the IED name from one field to another and then change it. The current behaviour makes this much harder than necessary...

**Comment by aus-betz** [comment]
It is handy to have the error reported immediately, however, the behaviour of jumping back to the top of the list when validation fails is rather annoying. I ended up copying the name minus the specific IED number so that it wouldn't cause duplicate names each time I pasted the data.

Realistically, this is a low priority topic relative to some of the other work that could be done!

**Comment by danyill** [comment]
Thansk for the report, I think I have an adequate fix, please test.

I have deployed to https://transpower-nz.github.io/open-scd/, suggest hard refresh (Ctrl+F5) to reload.

**Comment by aus-betz** [comment]
> Thansk for the report, I think I have an adequate fix, please test.
> 
> I have deployed to https://transpower-nz.github.io/open-scd/, suggest hard refresh (Ctrl+F5) to reload.

Confirmed as resolved - thanks.
